### ISSUE TITLE
Interactive Geospatial Visualization

### ISSUE THREAD

**Issue by bhaskarvk** [RConsortium/wishlist#12]
As much as I love the [leaflet](rstudio/leaflet) package for interactive geospatial visualization, there is certainly room for improvement and possibility of providing even more options to end users.
I have 3 sub projects of my own based on the leaflet package. But we can do even better.

- WebGL based fast modern dataviz using MapboxGL
- ESRI/ArcGIS backed dataviz using Argis JS API
- d3 based datavis using d3geo

I believe that these options will truly bring modern Geospatial Visualization to R and help it gain more market share especially in the GIS world.

**Comment by bhaskarvk** [comment]
BTW I plan to submit a proper proposal for this, but interested in finding out community interest first.

**Comment by jeff-mettel** [comment]
@bhaskarvk - Excellent idea.  First class geospatial tools in R would be a tremendous value-add to the ecosystem.

**Comment by ghost** [comment]
I really like this idea and would be interested in implementing the D3 and WebGL packages. Another thing to add: a nice interface to [Carto](http://carto.com) would be useful.

**Comment by mdsumner** [comment]
A problem in the existing R geospatial tools is that they tend to standardize on the limitations baked into "simple features" which is no topology in the sense of shared-vertices or shared-primitives, and no generalization from XY-Z. I have been working on a more general way of structuring these data, that works for transferring between GIS types to WebGL-ready types: 

https://github.com/r-gris/rangl

It's unstable, while I'm in the middle of supporting the new sf package, and while I figure out how to do things better. A crux issue, is that of needing multiple tables to store vertices, parts, and the objects. Nested types work brilliantly for the sf model, but for real generalization and efficiency you need a shared vertex pool at least. I see this as a subset of the wish for a general network API:  https://github.com/RConsortium/wishlist/issues/16 

Rangl is in rough shape, but I think it's ready to prototype many 3D and 4D applications that no simple features based application can do - but that will also benefit from the modernization that's now available via the sf package. 

Also finally, this is an offer of support and to help! Even if my experiments don't seem useful in this context, I'm offering to help get data and examples into shape for what you want to do here.

**Comment by mdsumner** [comment]
It seems like regl is a promising new framework for WebGL, has anyone explored that from an R perspective?    https://github.com/regl-project/regl
