### ISSUE TITLE
Comprehensive web API wrapper for Geo services

### ISSUE THREAD

**Issue by bhaskarvk** [RConsortium/wishlist#13]
I have been tracking all the possible Geo web services, everything from routing, to elevation data to forward/reverse geocoding etc.
So far the major providers are 
- Google
- Bing
- Here
- Mapquest
- Mapbox
- CartoDB
- Mapzen
- And some other secondary players.

These providers provide near identical or at least partially overlapping features in their Geo APIs. I have seen disparate R packages which wrap some of these APIs. But these R pacakges are essentially developed without a common code base or R API, and don't provide comprehensive coverage of all the underlying APIs of the provider.
Hense I propose a single API wrapping package to cover all the major Geo API providers (listed above and any others I may have overlooked). The goal of the package will be to provide comprehensive API coverage, as well as uniform R idiomatic APIs regardless of the provider.

This is a rather an ambitious project but with the right funding and participation I believe it can be done and would provide a great resource to the R-Spatial community.

**Comment by bhaskarvk** [comment]
BTW I plan to submit a proper proposal for this, but interested in finding out community interest first.

**Comment by corynissen** [comment]
HERE used to have a free tier, but is now a paid application. Google maps has a paid tier as well as a free service. The issue I see with this is keeping up with all of the changes to the APIs, terms of service, API keys, etc. that will change over time. Writing the initial code to do this is one thing to consider, but the maintenance may be a considerable ongoing commitment.

**Comment by bhaskarvk** [comment]
@corynissen These are challenges that will need overcoming on an ongoing basis, but that's the nature of the game when working with external APIs. I am also fine with having individual packages for individual services, but at least they should be under a single umbrella project (think tidyverse-esque meta package at the top). My two main concerns are a) Uniform R API across providers b) Comprehensive support for each provider.

The free/paid is a non issue. I believe there's plenty of reason to support paid providers, and users willing to pay for them or already customers of these providers will benefit from it.

**Comment by corynissen** [comment]
I mentioned the free/paid thing as a development hurdle. It's hard to develop and debug for an API that you cannot access.

**Comment by bhaskarvk** [comment]
FWIW the providers I have mentioned above have fairly well documented API docs, so in theory it should be possible to wrap them even if we can't fully test them without paying. Also there is always an option of reaching out to the providers and asking for a free tier / developer access.

e.g. here's the documentation for HERE https://developer.here.com/rest-apis/documentation/enterprise-map-tile/topics/api-reference.html

I've collected all API refs for these providers, and played with them whereever possible.

**Comment by ghost** [comment]
Interesting idea. Would this be in the spirit of [Geopy](https://geopy.readthedocs.io/en/1.11.0/)?

**Comment by bhaskarvk** [comment]
@xaranke Indeed! I was not aware of Geopy, but good to know that other languages are also looking for ways to provide such an API wrapper.
